concurrency: null

camoufox:
  api_key: "test"
  solver_type:
#    - AntiTurnstileTaskProxyLess
    - HcaptchaCracker
  headless: "false"

worker:
  name: "tmp2"
  wss_url: "wss://103.39.79.162:8080/ws/worker/"
#  wss_url: "wss://capsolver.yxschool.cc:8998/ws/worker/"

apikey:
  gemini_api_key: "AIzaSyC1bRWM4tjbRrv1M64j7yaawdV5xiGYib4"

models:
  CHALLENGE_CLASSIFIER_MODEL: "gemini-2.0-flash-lite"  #识别验证码类
  IMAGE_CLASSIFIER_MODEL: "gemini-2.0-flash-thinking-exp-01-21"  #二选多类
  SPATIAL_POINT_REASONER_MODEL: "gemini-2.0-flash-thinking-exp-01-21"  #点选类
  SPATIAL_PATH_REASONER_MODEL: "gemini-2.0-flash-thinking-exp-01-21" #拖拽路径类



